ui: tape
browsers:
  - name: chrome
    version: 39..dev
  - name: firefox
    version: 35..latest
  - name: ie
    version: 8..11
  - name: safari
    version: 5..latest
  - name: iphone
    version: 5.0..latest
  - name: ipad
    version: 6.0..latest
  - name: android
    version: 4.0..latest
browserify:
  - transform:
      name: babelify
